services:
  - type: web
    name: creacritic
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd web_interface && python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0 